{% set name = "cylc-uiserver" %}
{% set version = "0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "4cc85a6680148cddd8f1fd714f772acb7c52487239b7c2b781bf543a51c099d1"

build:
  number: 1
  entry_points:
    - cylc-uiserver=cylc.uiserver.main:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - cylc-flow==8.0a1
    - graphene-tornado==2.1.1
    - jupyterhub>=1.0
    - pip >3
    - pytest
    - pytest-runner==4.4
    - python
    - setuptools
    - tornado>=6.0
  run:
    - cylc-flow==8.0a1
    - graphene-tornado==2.1.1
    - jupyterhub>=1.0
    - python >=3.7
    - tornado>=6.0

test:
  imports:
    - cylc.uiserver
  commands:
    - cylc-uiserver --help

about:
  home: "https://github.com/cylc/cylc-uiserver"
  license: "GNU General Public v3 (GPLv3)"
  license_family: "GPL3"
  license_file: ""
  summary: "Summary of the package"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - kinow
