{% set name = "cylc-flow" %}
{% set version = "8.0a1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  #git_url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  #sha256: "3588bef608d5bbd7911c627f88dbfad7c0553820be77317fa0b631201db43ba0"
  git_url: https://github.com/cylc/cylc-flow.git
  git_rev: bb5a1270e5a695e4a69c4f0d476d1c00d17ae81f

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - ansimarkup>=1.0.0
    - colorama>=0.4
    - graphene==2.1.6
    - jinja2 >=2.10.1
    - markupsafe>=1.1
    - metomi-isodatetime>=1!2.0.1
    - pip
    - protobuf>=3.7
    - pytest-runner
    - python >3
    - python-jose>=3.0
    - pyzmq>=18.0
  run:
    - ansimarkup>=1.0.0
    - colorama>=0.4
    - cryptography
    - graphene==2.1.6
    - jinja2 >=2.10.1
    - markupsafe>=1.1
    - metomi-isodatetime>=1!2.0.1
    - protobuf>=3.7
    - pyasn1
    - python >3
    - python-jose>=3.0
    - pyzmq>=18.0

test:
  imports:
    - cylc.flow
  commands:
    - cylc --version

about:
  home: "The package home page"
  license: "GNU General Public v3 (GPLv3)"
  license_family: "GPL3"
  license_file: ""
  summary: "Summary of the package"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - kinow
