{% set name = "cylc-flow" %}
{% set version = "8.0a1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "36f4f4363cb5cc7a3a613d2db6e84cc41c2825c6cd011191cc4821c5ca9c81a4"

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - ansimarkup>=1.0.0
    - colorama>=0.4
    - graphene==2.1.6
    - jinja2 >=2.10.1
    - markupsafe>=1.1
    - metomi-isodatetime>=1!2.0.1
    - pip
    - protobuf>=3.7
    - pytest-runner
    - python >=3.7
    - python-jose>=3.0
    - pyzmq>=18.0
  run:
    - ansimarkup>=1.0.0
    - colorama>=0.4
    - cryptography
    - graphene==2.1.6
    - jinja2 >=2.10.1
    - markupsafe>=1.1
    - metomi-isodatetime>=1!2.0.1
    - protobuf>=3.7
    - pyasn1
    - python >=3.7
    - python-jose>=3.0
    - pyzmq>=18.0

test:
  imports:
    - cylc.flow
  commands:
    - cylc --version

about:
  home: "The package home page"
  license: "GNU General Public v3 (GPLv3)"
  license_family: "GPL3"
  license_file: ""
  summary: "Summary of the package"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - kinow
