{% set name = "cylc" %}
{% set version = "8.0" %}
# Cylc Xtriggers
#{% set xtriggers_hash = "a83eb011021cf67f96e79c14f4e003fa7d3f2ab8" %}
# Cylc UI
{% set ui_version = "0.6-special" %}
{% set ui_hash = "f5a8dccf29ae304e0871434aaad25540c5c159f641997d0b66c5d89a0669724d" %}

package:
  name: '{{ name|lower }}'
  version: "{{ version }}"

source:
  # Cylc UI
  - url: https://github.com/kinow/cylc-ui/releases/download/{{ ui_version }}/cylc-ui-{{ ui_version }}-dist.zip
    sha256: {{ ui_hash }}
    folder: cylc-ui

build:
  # Skip as Cylc requires Linux
  skip: True  # [not linux]
  number: 0

requirements:
  host:
    - python >3
  run:
    - python >3
    - cylc-flow==8.0a1
    - cylc-uiserver==1.0

test:
  imports:
    - cylc.flow
    - cylc.uiserver
    # - cylc.xtriggers.echo
  commands:
    - cylc --version
    - cylc-uiserver --help

about:
  home: https://cylc.github.io
  license: GPL-2.0+
  license_family: GPL2
  license_file: ''
  summary: A workflow engine for cycling systems
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
