{% set name = "cylc" %}
{% set version = "8.0a1" %}
# Cylc Xtriggers
#{% set xtriggers_hash = "a83eb011021cf67f96e79c14f4e003fa7d3f2ab8" %}
# Cylc UI
{% set ui_version = "0.1" %}
{% set ui_hash = "639b18bb7526914203ffdc6bd80f2b580683c63e3d94c4b92d1bb00355824b44" %}

package:
  name: '{{ name|lower }}'
  version: "{{ version }}"

source:
  # Cylc UI
  - url: https://github.com/cylc/cylc-ui/releases/download/{{ ui_version }}/cylc-ui-{{ ui_version }}-dist.zip
    sha256: {{ ui_hash }}
    folder: cylc-ui

build:
  # Skip as Cylc requires Linux
  skip: True  # [not linux]
  number: 2

requirements:
  host:
    - python >=3.7
  run:
    - cylc-flow==8.0a1
    - cylc-uiserver==0.1
    - python >=3.7
    - 'configurable-http-proxy >=4.1'

test:
  imports:
    - cylc.flow
    - cylc.uiserver
    # - cylc.xtriggers.echo
  commands:
    - cylc --version
    - cylc-uiserver --help
    - configurable-http-proxy -V

about:
  home: https://cylc.github.io
  license: GPL-2.0+
  license_family: GPL2
  license_file: ''
  summary: A workflow engine for cycling systems
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
